name: Flutter Build Releases
on: workflow_dispatch
jobs:
 flutter-releases-apk:
   runs-on: macos-latest
   steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
       java-version: '12.x'
    - name: Flutter Configuration
      uses: subosito/flutter-action@v1
    - name: Get Packages
      run: flutter pub get
    - name: Build APK
      run: flutter build apk --release
    - name: Rest UI Release
      uses: actions/upload-artifact@v2.2.4
      with:
       name: Rest UI Release
       path: build/app/outputs/apk/release/app-release.apk
